version: "3"   # 파일규격버전

services:
    db:   # 서비스이름
        image: 0627ec6901db  # 이미지
        container_name: mysql-st   # 컨테이너 이름
        ports:
        - "3307:3306"   # 포트 설정  외부:내부
        environment:
            MYSQL_ROOT_PASSWORD: "food123!"   # 패스워드설정
            MYSQL_USER: "food"
            MYSQL_PASSWORD: "food123!"
            MYSQL_DATABASE: "food"
        command:
        - --character-set-server=utf8mb4      # 인코딩
        - --collation-server=utf8mb4_unicode_ci
        volumes:
        - /Users/bean/docker-compose/self-st-mysql/data
